[package]
name = "r1csipa"
version = "0.1.0"
edition = "2021"
description = "R1CS to IPA transformation with zero-knowledge and committed-input support"
license = "MIT"
repository = "https://github.com/hpicrypto/ecdsa_pops"

[lib]
doctest = false

[dependencies]
halo2curves = { workspace = true }
merlin = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
ark-std = { workspace = true }
rayon = "1.8"
subtle = "2.2.1"
rand_core = { workspace = true }
bellpepper-core = { workspace = true }


[dev-dependencies]
rand = "0.8"

[features]
print-trace = ["ark-std/print-trace"]
asm = ["halo2curves/asm"]
