[package]
name = "ecdsa_pops"
version = "0.1.0"
edition = "2021"
description = "Implementations of ECDSA-based PoPs"
repository = "https://github.com/hpicrypto/ecdsa_pops"
license = "MIT"

[lib]
doctest = false

[dependencies]
bellpepper-core = { workspace = true }
bellpepper = { workspace = true }
ff = { workspace = true }

merlin = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
ark-std = { workspace = true }
ark-ff = { workspace = true }
ark-ec = { workspace = true }
ark-serialize = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
rand_core = { workspace = true }
thiserror = { workspace = true }
r1csipa = { path = "../r1csipa/" }
rok = { path = "../rok/" }

halo2curves = { workspace = true }

# Need for equality across groups
ark-secp256r1 = { version = "^0.4.0", default-features = false }


equality_across_groups = { git = "https://github.com/alexandroszacharakis8/docknetwork-crypto" }
dock_crypto_utils = { git = "https://github.com/alexandroszacharakis8/docknetwork-crypto" }

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[features]
# default = ["print-trace"]
print-trace = ["ark-std/print-trace", "r1csipa/print-trace"]
asm = ["halo2curves/asm"]

[[bench]]
name = "pop_native"
harness = false

[[bench]]
name = "pop_sigma"
harness = false
